#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout
  methods: GET

webhook:
  path: /payment/webhook
  defaults: {_controller: App\Controller\CartController::catchWebhook}
  methods: POST
